default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres  # db에 접근하기 위한 ID
  password: postgres  # db에 접근하기 위한 Password
  host: localhost
  template: template0

development:
  <<: *default
  database: dev_db

test:
  <<: *default
  database: test_db

production:
  <<: *default
  database: pd_db